version: '3.8'

services:
  eureka-server:
    image: mariammseddi12/eureka-server
    container_name: eureka-server
    hostname: eureka.systeo.tn
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - systeo-network

  gateway-service:
    image: mariammseddi12/gateway-service
    container_name: gateway-service
    hostname: m1.systeo.tn
    ports:
      - "9090:9090"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

  compain-service:
    image: mariammseddi12/compain-service
    container_name: compain-service
    hostname: m2.systeo.tn
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

  facturation-service:
    image: mariammseddi12/facturation-service
    container_name: facturation-service
    hostname: m5.systeo.tn
    ports:
      - "8024:8024"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

  depense-service:
    image: mariammseddi12/depense-service
    container_name: depense-service
    hostname: m4.systeo.tn
    ports:
      - "8022:8022"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

  bank-service:
    image: mariammseddi12/bank-service
    container_name: bank-service
    hostname: m3.systeo.tn
    ports:
      - "8021:8021"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

  reglemetnaffecatation-service:
    image: mariammseddi12/reglemetnaffecatation-service
    container_name: reglemetnaffecatation-service
    hostname: m6.systeo.tn
    ports:
      - "8025:8025"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

  document-service:
    image: mariammseddi12/document-service
    container_name: document-service
    hostname: m7.systeo.tn
    ports:
      - "8023:8023"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - systeo-network

networks:
  systeo-network:
    driver: bridge
