apiVersion: apps/v1
kind: Deployment
metadata:
  name: reglemetnaffecatation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reglemetnaffecatation-service
  template:
    metadata:
      labels:
        app: reglemetnaffecatation-service
    spec:
      containers:
      - name: reglemetnaffecatation-service
        image: mariammseddi12/reglemetnaffecatation-service:latest
        ports:
        - containerPort: 8025
        env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"

apiVersion: v1
kind: Service
metadata:
  name: reglemetnaffecatation-service
spec:
  selector:
    app: reglemetnaffecatation-service
  ports:
  - port: 8025
    targetPort: 8025
